name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wemogy/get-release-version-action@v3.0.3
        id: get-release-version

      - name: Create GitHub Release
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-version-tag: ${{ steps.get-release-version.outputs.version-name }}
          release-title: Version ${{ steps.get-release-version.outputs.version }}
